apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "node-local-dns.serviceAccountName" . }}
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile

